skinparam activity {
  StartColor #e0e0e0
  EndColor #e0e0e0
  BarColor #e0e0e0
  BackgroundColor #508050
  BorderColor #e0e0e0

  FontColor #ffffff
}

skinparam state {
  BackgroundColor #508050
}

skinparam usecase {
  ArrowColor #e0e0e0
  ArrowFontColor #ffffff

  BorderColor #e0e0e0
  BackgroundColor #508050
  FontColor #ffffff
  AttributeFontColor #ffffff
  StereotypeFontColor #e0e0e0
}

skinparam actor {
  BorderColor #e0e0e0
  BackgroundColor #508050
  FontColor #ffffff
}

skinparam package {
  BackgroundColor #c0c0a0
}

(*) --> アクションA

if "条件" then
  -> [Yes] アクションB
  --> (*)
else
  --> [No] (*)
endif
