abstract 捕獲アイテム
捕獲アイテム <|-- モンスターボール
捕獲アイテム <|-- スーパーボール
捕獲アイテム <|-- ハイパーボール
捕獲アイテム <|-- マスターボール

モンスター <|-- 仲間モンスター

プレイヤー "1" o-- "0..*" 捕獲アイテム
捕獲アイテム "1" -- "0..1" モンスター
プレイヤー "1" <--> "0..*" 仲間モンスター
